version: '3.7'
services:
  #PHP Service
  goodboi_api :
    build:
      context: .
      dockerfile: Dockerfileprod
    image: digitalocean.com/php
    container_name: goodboi_api
    restart: unless-stopped
    environment:
      SERVICE_NAME: goodboi_api
      SERVICE_TAGS: dev
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - app

  webserver:
    image: nginx:1.17-alpine
    container_name: webserver
    restart: unless-stopped
    tty: true
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www
      - ./nginx:/etc/nginx/conf.d/
    networks:
      - app

  db:
    container_name: goodboi_db
    image: mariadb:10.4.8-bionic
    environment:
      MYSQL_USER : root
      MYSQL_PASSWORD: rootpass
      MYSQL_ROOT_PASSWORD: rootpass
    volumes:
      - .mariadb-data:/var/lib/mysql #connect local files with container files
    networks:
      - app
    ports:
      - 3306:3306

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin1
    ports:
      - 8080:8080
    environment:
      PMA_HOST: db
      MYSQL_USER: user
      MYSQL_PASSWORD: supersecret
    depends_on:
      - db
    networks:
      - app

networks:
  app:
   driver: bridge