version: '3.7'
services:
  #PHP Service
  goodboi_api :
    build:
      context: .
      dockerfile: Dockerfileprod
    image: digitalocean.com/php
    container_name: goodboi_api
    restart: unless-stopped
    environment:
      SERVICE_NAME: goodboi_api
      SERVICE_TAGS: dev
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - app

  webserver:
    image: nginx:1.17-alpine
    container_name: webserver
    restart: unless-stopped
    tty: true
    ports:
      - "80:80"
      - "443:443" 
    volumes:
      - ./:/var/www
      - ./nginx:/etc/nginx/conf.d/:ro
      - ./nginx:/etc/nginx/nginx.conf/:ro
#      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot/:ro
      - ./certbot/conf/:/etc/nginx/ssl/:ro

    networks:
      - app

  goodboi_production:
    container_name: goodboi_db
    image: mariadb:10.4.8-bionic
    environment:
      MYSQL_USER : root
      MYSQL_PASSWORD: rootpass
      MYSQL_ROOT_PASSWORD: rootpass
    volumes:
      - .mariadb-data:/var/lib/mysql #connect local files with container files
    networks:
      - app
    ports:
      - 3306:3306

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin1
    ports:
      - 8080:8080
    environment:
      PMA_HOST: goodboi_production
      MYSQL_USER: user
      MYSQL_PASSWORD: supersecret
    depends_on:
      - goodboi_production
    networks:
      - app
  certbot:
    image: certbot/certbot:latest
    container_name: certbot
    volumes: 
      - ./certbot/conf:/etc/letsencrypt/:rw
      - ./certbot/www/:/var/www/certbot/:rw
    #command: certonly --webroot -w /var/www/certbot --force-renewal --email georgex8@gmail.com  -d api.goodboi.com.cy  --agree-tos
    networks: 
      - app

networks:
  app:
   driver: bridge
